openapi: 3.0.3
info:
  title: Notifications
  contact: {}
  version: '1.0'
  description: |
    #Overview:

    This API pushes the new statement notifications from SDES to customs-financials-frontend service through API platform.
    In service Notifications are displayed to users when they have new statements and have logged in for the first time.
    Notifications will be disappeared when the users view the statement.

    #Versioning:

    https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md

    #Errors:

    https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
servers:
  - url: https://test-api.service.hmrc.gov.uk/
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk/
    description: Production
    variables: {}
paths:
  /customs/statements/metadata:
    post:
      tags:
        - customs
      summary: CustomsStatementsMetadata_POST
      description: >
        This resource sends new document notifications which are stored in Mongo. Customs financials frontend utilises the stored data to send email notifications and in-service notifications.
      operationId: CustomsStatementsMetadata_POST
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CustomsStatementsMetadatarequest'
              description: ''
              example:
                - eori: GB12368739854792
                  fileName: vat-2018-02.pdf
                  fileSize: '66944'
                  metadata:
                    - metadata: PeriodStartYear
                      value: '2018'
                    - metadata: PeriodStartMonth
                      value: '2'
                    - metadata: FileType
                      value: PDF
                    - metadata: FileRole
                      value: C79Certificate
            example:
              - eori: GB12368739854792
                fileName: vat-2018-02.pdf
                fileSize: '66944'
                metadata:
                  - metadata: PeriodStartYear
                    value: '2018'
                  - metadata: PeriodStartMonth
                    value: '2'
                  - metadata: FileType
                    value: PDF
                  - metadata: FileRole
                    value: C79Certificate
        required: true
      security:
        - applicationRestricted: []
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/CustomsStatementsMetadataresponse'
                  - description: Valid response
                    example:
                      Status: Ok
              example:
                Status: Ok
        '400':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/CustomsStatementsMetadataresponse400'
                  - example:
                      errors:
                        - path: obj[0].fileType
                          error: error.path.missing
              example:
                errors:
                  - path: obj[0].fileType
                    error: error.path.missing
      deprecated: false
components:
  securitySchemes:
    applicationRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating application restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints for details.
      flows:
        clientCredentials:
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          scopes: {}
  schemas:
    CustomsStatementsMetadatarequest:
      title: CustomsStatementsMetadatarequest
      required:
        - eori
        - fileName
        - fileSize
        - metadata
      type: object
      properties:
        eori:
          type: string
        fileName:
          type: string
        fileSize:
          type: string
        metadata:
          type: array
          items:
            $ref: '#/components/schemas/Metadatum'
          description: ''
      example:
        eori: GB12368739854792
        fileName: vat-2018-02.pdf
        fileSize: '66944'
        metadata:
          - metadata: PeriodStartYear
            value: '2018'
          - metadata: PeriodStartMonth
            value: '2'
          - metadata: FileType
            value: PDF
          - metadata: FileRole
            value: C79Certificate
    Metadatum:
      title: Metadatum
      required:
        - metadata
        - value
      type: object
      properties:
        metadata:
          type: string
        value:
          type: string
      example:
        metadata: PeriodStartYear
        value: '2018'
    CustomsStatementsMetadataresponse:
      title: CustomsStatementsMetadataresponse
      required:
        - Status
      type: object
      properties:
        Status:
          type: string
      example:
        Status: Ok
    Error:
      title: Error
      required:
        - path
        - error
      type: object
      properties:
        path:
          type: string
        error:
          type: string
      example:
        path: obj[0].fileType
        error: error.path.missing
    CustomsStatementsMetadataresponse400:
      title: CustomsStatementsMetadataresponse400
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
          description: ''
      example:
        errors:
          - path: obj[0].fileType
            error: error.path.missing
tags:
  - name: customs
    description: ''
